'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Calculator
    
    '''<summary>
    '''fname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dob As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadioButtonList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList1 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtfmv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfmv As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''bequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bequest As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''conserve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents conserve As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''calcbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calcbtn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CashWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CashWS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''bx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bx As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TotCashWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotCashWS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TIValueWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TIValueWS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tax As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tinhome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tinhome As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ce As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''walk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents walk As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''term control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents term As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''adj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Total As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''help_conserve_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents help_conserve_Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''help_bequest_Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents help_bequest_Literal As Global.System.Web.UI.WebControls.Literal
End Class
