<?xml version="1.0" encoding="utf-8"?><Database Name="lsp_calc" Class="mortalityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=wbase2.database.windows.net;Initial Catalog=lsp_calc;Persist Security Info=True;User ID=robbk13" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="lsp_calcConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MortabilitySearchable" Member="MortabilitySearchables">
    <Type Name="MortabilitySearchable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SourceName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GenderNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Probability" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>